server {
  listen 80;
  root   /usr/share/nginx/html;
  index  index.html;

  # Serve the Vue single-page app and fallback to index.html for client-side routing.
  location / {
    try_files $uri $uri/ /index.html;
  }
}
