// file: service/api/api-handler.go
package api

import (
	"net/http"

	"github.com/julienschmidt/httprouter"
)

/*
RegisterRoutes wires all HTTP endpoints to their handlers.

This router is kept 1:1 aligned with the OpenAPI spec:
  - No global "/api" prefix.
  - No CORS preflight helper endpoint (the spec removed /cors).
  - Only the endpoints required by the assignment are exposed here.
    (If you need dev-only helpers, put them in a separate file.)
*/
func (rt *_router) RegisterRoutes() {
	// -------------------- Public (no auth) --------------------

	// POST /session -> doLogin (returns 200 on success per spec)
	rt.router.POST("/session", rt.doLogin)

	// POST /register -> doRegister (returns 201 on success)
	rt.router.POST("/register", rt.doRegister)

	// GET /liveness -> simple service liveness check
	rt.router.GET("/liveness", rt.liveness)

	// GET /healthz -> simple health check
	rt.router.GET("/healthz", rt.healthz)

	// -------------------- Protected (auth required) --------------------
	// All handlers registered below must use rt.wrap(...) to inject auth / context.

	// Conversations
	// POST /conversations -> startConversation
	rt.router.POST("/conversations", rt.wrap(rt.startConversation))
	// GET /conversations -> getMyConversations
	rt.router.GET("/conversations", rt.wrap(rt.getMyConversations))
	// DELETE /conversations/{id} -> deleteConversation
	rt.router.DELETE("/conversations/:id", rt.wrap(rt.deleteConversation))

	// Users
	// PUT /users/set_username -> setMyUserName
	// NOTE: despite path name, this updates the user's display name ("name") per spec.
	rt.router.PUT("/users/set_username", rt.wrap(rt.setMyUserName))
	// PUT /users/set_photo -> setMyPhoto (multipart/form-data)
	rt.router.PUT("/users/set_photo", rt.wrap(rt.setMyPhoto))
	// GET /users/me -> getUserInfo
	rt.router.GET("/users/me", rt.wrap(rt.getUserInfo))
	// GET /users/search?q=... -> searchUsers
	rt.router.GET("/users/search", rt.wrap(rt.searchUsers))
	// GET /users/profile/{userId} -> getUserProfile
	// NOTE: path param name must be "userId" to match the spec.
	rt.router.GET("/users/profile/:userId", rt.wrap(rt.getUserProfile))

	// Groups
	// POST /groups -> createGroup
	rt.router.POST("/groups", rt.wrap(rt.createGroup))
	// GET /groups -> getGroupsList
	rt.router.GET("/groups", rt.wrap(rt.getGroupsList))
	// GET /groups/{id} -> getGroupDetail
	rt.router.GET("/groups/:id", rt.wrap(rt.getGroupDetail))
	// PUT /groups/{id}/name -> setGroupName
	rt.router.PUT("/groups/:id/name", rt.wrap(rt.setGroupName))
	// PUT /groups/{id}/photo -> setGroupPhoto (multipart/form-data)
	rt.router.PUT("/groups/:id/photo", rt.wrap(rt.setGroupPhoto))
	// POST /groups/{id}/members -> addToGroup
	rt.router.POST("/groups/:id/members", rt.wrap(rt.addToGroup))
	// DELETE /groups/{id}/members -> leaveGroup
	rt.router.DELETE("/groups/:id/members", rt.wrap(rt.leaveGroup))

	// Messages
	// GET /messages?conversationId=...&limit=...&beforeCursor=...&afterCursor=... -> getConversation
	// IMPORTANT: the query key is "conversationId" (camelCase) to match the spec.
	rt.router.GET("/messages", rt.wrap(rt.getMessages))
	// POST /messages -> sendMessage
	rt.router.POST("/messages", rt.wrap(rt.sendMessage))
	// GET /messages/{id} -> getMessageByID
	rt.router.GET("/messages/:id", rt.wrap(rt.getMessageByID))
	// DELETE /messages/{id} -> deleteMessage
	rt.router.DELETE("/messages/:id", rt.wrap(rt.deleteMessage))
	// POST /messages/{id}/forward -> forwardMessage
	rt.router.POST("/messages/:id/forward", rt.wrap(rt.forwardMessage))
	// GET /messages/{id}/comment -> getMessageComments
	rt.router.GET("/messages/:id/comment", rt.wrap(rt.getMessageComments))
	// POST /messages/{id}/comment -> commentMessage
	rt.router.POST("/messages/:id/comment", rt.wrap(rt.commentMessage))
	// POST /messages/{id}/uncomment -> uncommentMessage
	rt.router.POST("/messages/:id/uncomment", rt.wrap(rt.uncommentMessage))

	// -------------------- Static files --------------------
	// Serve uploaded files from the local "uploads" directory.
	// This matches the public URLs generated by publicURL(...), e.g. /uploads/users/...
	rt.router.ServeFiles("/uploads/*filepath", http.Dir("uploads"))
}

// healthz returns a simple OK JSON for health checks (for nginx /api/healthz proxy).
func (rt *_router) healthz(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(`{"ok":true}`))
}