package api

import "net/http"

/*
RegisterRoutes wires all HTTP endpoints to their handlers.

This router is kept 1:1 aligned with the OpenAPI spec:
  - No global "/api" prefix.
  - No CORS preflight helper endpoint (the spec removed /cors).
  - Only the endpoints required by the assignment are exposed here.
    (If you need dev-only helpers, put them in a separate file.)
*/
func (rt *_router) RegisterRoutes() {
	// -------------------- Public (no auth) --------------------

	// POST /session -> doLogin (returns 201 on success per spec text; our handler returns 201)
	rt.router.POST("/session", rt.doLogin)

	// POST /register -> doRegister (returns 201 on success)
	rt.router.POST("/register", rt.doRegister)

	// GET /liveness -> simple service liveness check
	rt.router.GET("/liveness", rt.liveness)

	// -------------------- Protected (auth required) --------------------
	// All handlers registered below must use rt.wrap(...) to inject auth / context.

	// Conversations
	// POST /conversations -> startConversation
	rt.router.POST("/conversations", rt.wrap(rt.startConversation))
	// GET /conversations -> getMyConversations
	rt.router.GET("/conversations", rt.wrap(rt.getMyConversations))

	// Users
	// PUT /users/set_username -> setMyUserName
	rt.router.PUT("/users/set_username", rt.wrap(rt.setMyUserName))
	// PUT /users/set_photo -> setMyPhoto (multipart/form-data)
	rt.router.PUT("/users/set_photo", rt.wrap(rt.setMyPhoto))
	// GET /users/me -> getUserInfo
	rt.router.GET("/users/me", rt.wrap(rt.getUserInfo))
	// GET /users/search?q=... -> searchUsers
	rt.router.GET("/users/search", rt.wrap(rt.searchUsers))
	// GET /users/profile/{userId} -> getUserProfile
	// NOTE: path param name must be "userId" to match the spec.
	rt.router.GET("/users/profile/:userId", rt.wrap(rt.getUserProfile))

	// Groups
	// POST /groups -> createGroup
	rt.router.POST("/groups", rt.wrap(rt.createGroup))
	// GET /groups -> getGroupsList
	rt.router.GET("/groups", rt.wrap(rt.getGroupsList))
	// GET /groups/{id} -> getGroupDetail
	rt.router.GET("/groups/:id", rt.wrap(rt.getGroupDetail))
	// PUT /groups/{id}/name -> setGroupName
	rt.router.PUT("/groups/:id/name", rt.wrap(rt.setGroupName))
	// PUT /groups/{id}/photo -> setGroupPhoto (multipart/form-data)
	rt.router.PUT("/groups/:id/photo", rt.wrap(rt.setGroupPhoto))
	// POST /groups/{id}/members -> addToGroup
	rt.router.POST("/groups/:id/members", rt.wrap(rt.addToGroup))
	// DELETE /groups/{id}/members -> leaveGroup
	rt.router.DELETE("/groups/:id/members", rt.wrap(rt.leaveGroup))

	// Messages
	// GET /messages?conversationId=...&limit=...&beforeCursor=...&afterCursor=... -> getConversation
	// IMPORTANT: the query key is "conversationId" (camelCase) to match the spec.
	rt.router.GET("/messages", rt.wrap(rt.getMessages))
	// POST /messages -> sendMessage
	rt.router.POST("/messages", rt.wrap(rt.sendMessage))
	// GET /messages/{id} -> getMessageByID
	rt.router.GET("/messages/:id", rt.wrap(rt.getMessageByID))
	// DELETE /messages/{id} -> deleteMessage
	rt.router.DELETE("/messages/:id", rt.wrap(rt.deleteMessage))
	// POST /messages/{id}/forward -> forwardMessage
	rt.router.POST("/messages/:id/forward", rt.wrap(rt.forwardMessage))
	// GET /messages/{id}/comment -> getMessageComments
	rt.router.GET("/messages/:id/comment", rt.wrap(rt.getMessageComments))
	// POST /messages/{id}/comment -> commentMessage
	rt.router.POST("/messages/:id/comment", rt.wrap(rt.commentMessage))
	// POST /messages/{id}/uncomment -> uncommentMessage
	rt.router.POST("/messages/:id/uncomment", rt.wrap(rt.uncommentMessage))

	// -------------------- Static files --------------------
	// Serve uploaded files from the local "uploads" directory.
	// This matches the public URLs generated by publicURL(...), e.g. /uploads/users/...
	rt.router.ServeFiles("/uploads/*filepath", http.Dir("uploads"))
}

/*
NOTE about compatibility aliases:

We intentionally DO NOT register any alias routes here
(e.g., /users/me/name, /users/me/photo, /start-conversation,
 /conversations/:conversationId, etc.), because they are not
declared in the OpenAPI and would drift the implementation.

If you ever need them for dev/testing, create a separate file
(e.g., api_aliases_dev.go) and protect their registration behind
a build tag or environment flag. When adding such aliases, ensure
they set query keys using "conversationId" (camelCase), not "conversation_id".
*/
